name: Clone wycheproof
description: Clones the wycheproof repository

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      with:
        repository: "google/wycheproof"
        path: "wycheproof"
        ref: "master"
